import fs from 'node:fs/promises'

test('the Windows cmd launcher prefers PowerShell 7 and falls back to Windows PowerShell', async () => {
  const launcher = await fs.readFile('start-game.cmd', 'utf8')
  expect(launcher).toContain('PowerShell\\7\\pwsh.exe')
  expect(launcher).toContain('where pwsh')
  expect(launcher).toContain('WindowsPowerShell\\v1.0\\powershell.exe')
  expect(launcher).toContain('if not defined TMN_PWSH')
  expect(launcher).toContain('start "" "%TMN_PWSH%"')
  expect(launcher).toContain('-WindowStyle Hidden')
  expect(launcher).toContain('-File "%~dp0start-game.ps1"')
  expect(launcher.indexOf('PowerShell\\7\\pwsh.exe'))
    .toBeLessThan(launcher.indexOf('where pwsh'))
  expect(launcher.indexOf('where pwsh'))
    .toBeLessThan(launcher.indexOf('WindowsPowerShell\\v1.0\\powershell.exe'))
})

test('the Windows launcher calibrates a 1920 by 1080 game viewport', async () => {
  const launcher = await fs.readFile('start-game.ps1', 'utf8')
  expect(launcher).toContain('$env:TMN_POWERSHELL')
  expect(launcher).toContain('GetCurrentProcess()')
  expect(launcher).toContain('MainModule.FileName')
  expect(launcher).toContain("'pwsh.exe'")
  expect(launcher).toContain("'powershell.exe'")
  expect(launcher.indexOf('$env:TMN_POWERSHELL'))
    .toBeLessThan(launcher.indexOf('Start-Process `'))
  expect(launcher).toContain('$GameViewportWidth = 1920')
  expect(launcher).toContain('$GameViewportHeight = 1080')
  expect(launcher).toContain('Set-TypingManiaNovelGameViewport')
  expect(launcher).toContain('GetLargestChildClientRect')
  expect(launcher).toContain('Chrome_RenderWidgetHostHWND')
  expect(launcher).toContain('GetWindowRect')
  expect(launcher).toContain('SetWindowPos')
  expect(launcher).toContain('"--window-size=$GameWindowSize"')
  expect(launcher).toContain('Import-WindowsProxyEnvironment')
  expect(launcher).toContain('$env:TMN_SYSTEM_HTTP_PROXY')
  expect(launcher).toContain('$env:TMN_SYSTEM_HTTPS_PROXY')
  expect(launcher).toContain('$env:TMN_SYSTEM_NO_PROXY')
  expect(launcher).toContain("@('--use-env-proxy')")
})
